### ISSUE TITLE
Issue with tools (msys2)

### ISSUE THREAD

**Issue by oolio151** [pret/pokeemerald#1647]
When installing the packages to make pokeemerald using msys2, I ran into these errors and I could not install the packages, It happens for a few other files and eventually errors out. 
![image](https://user-images.githubusercontent.com/97859173/159801701-c88acb51-5697-4022-ba5c-9d4e6a97552b.png)

**Comment by LOuroboros** [comment]
> When installing the packages to make pokeemerald using msys2, I ran into these errors and I could not install the packages, It happens for a few other files and eventually errors out. ![image](https://user-images.githubusercontent.com/97859173/159801701-c88acb51-5697-4022-ba5c-9d4e6a97552b.png)

`pacman -Sy msys2-keyring`, and then run `pacman -S make gcc zlib-devel git` again.

Do keep in mind that while the INSTALL.md document currently suggests to install the `mingw-w64-x86_64-libpng` package, this doesn't work, or at least it hasn't worked for me as the compiler complained that libpng wasn't found on MSys2 and predictively gave me an error telling me that png.h was missing. Building libpng from the source code does work though. I explain how to do that [here](https://www.pokecommunity.com/showthread.php?t=425246).

**Comment by coltongit** [comment]
Has there been any updates on this issue? If not, I could try to update the document with building it from source in a PR.

**Comment by coltongit** [comment]
Fixed in #1683

**Comment by Cofflag** [comment]
I‘v met the problem few days ago, and here is how I solve it:
open /etc/pacman.conf, change the 'SigLevel' in the section core :
[core]
#SigLevel = PackageRequired
 
SigLevel = Never

-----

**Comment by SiliconExarch** [comment]
> > When installing the packages to make pokeemerald using msys2, I ran into these errors and I could not install the packages, It happens for a few other files and eventually errors out. ![image](https://user-images.githubusercontent.com/97859173/159801701-c88acb51-5697-4022-ba5c-9d4e6a97552b.png)
> 
> `pacman -Sy msys2-keyring`, and then run `pacman -S make gcc zlib-devel git` again.
> 
> Do keep in mind that while the INSTALL.md document currently suggests to install the `mingw-w64-x86_64-libpng` package, this doesn't work, or at least it hasn't worked for me as the compiler complained that libpng wasn't found on MSys2 and predictively gave me an error telling me that png.h was missing. Building libpng from the source code does work though. I explain how to do that [here](https://www.pokecommunity.com/showthread.php?t=425246).

While it is necessary to update the keyring manually either way, it sounds like you missed the part where INSTALL.md tells you to specifically launch the mingw64 environment, as opposed to opening it from the start menu icon that devkitPro installs. I just verified with a clean install of devkitPro and libpng was located successfully after installing the packaged version as suggested.

**Comment by GriffinRichards** [comment]
8ec0bff0342413ac4996b63382c8d03a3b532899
